local map = vim.keymap.set

map("n", "<leader>pv", vim.cmd.Ex, { desc = "Open netrw" })
map("v", "J", ":m '>+1<CR>gv=gv", { desc = "Move selection down" })
map("v", "K", ":m '<-2<CR>gv=gv", { desc = "Move selection up" })
map("n", "J", "mzJ`z", { desc = "Join line (keep cursor)" })
map("n", "<C-d>", "<C-d>zz", { desc = "Half-page down (centred)" })
map("n", "<C-u>", "<C-u>zz", { desc = "Half-page up (centred)" })
map("n", "n", "nzzzv", { desc = "Next match (centred)" })
map("n", "N", "Nzzzv", { desc = "Prev match (centred)" })
map("x", "<leader>p", "\"_dP", { desc = "Paste without yanking" })
map("v", "<leader>y", "\"+y", { desc = "Yank to system clipboard" })
map("v", "<leader>Y", "\"+Y", { desc = "Yank line to system clipboard" })
map("n", "<C-k>", "<cmd>cnext<CR>zz", { desc = "Next quickfix item" })
map("n", "<C-j>", "<cmd>cprev<CR>zz", { desc = "Prev quickfix item" })
map("n", "<leader>k", "<cmd>lnext<CR>zz", { desc = "Next loclist item" })
map("n", "<leader>j", "<cmd>lprev<CR>zz", { desc = "Prev loclist item" })
map("n", "<leader>s", ":%s/\\<<C-r><C-w>\\>/<C-r><C-w>/gI<Left><Left><Left>", { desc = "Substitute word under cursor" })
map("n", "<leader>x", "<cmd>!chmod +x %<CR>", { silent = true, desc = "Make file executable" })
