#####################################################
# Set default terminal
#####################################################
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-kitty:RGB"

#####################################################
# Reload config
#####################################################
unbind r
bind r source-file ~/.config/tmux/tmux.conf; display-message "reloaded"

#####################################################
# Vim style pane selection
#####################################################
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Start windows and panes at 1, not 0
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

#####################################################
# set options
#####################################################
set -g mouse on
set -g repeat-time 1000
set-option -g status-position bottom
set -sg escape-time 10
set -g mode-keys vi
set -g focus-events on
set -g history-limit 10000

#####################################################
# Shift arrow to switch windows
#####################################################
bind -n S-Left  previous-window
bind -n S-Right next-window

#####################################################
# split pane bindings
#####################################################
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
