# terminal + true colour
source-file /etc/theme/tmux.conf
set -g default-terminal "tmux-256color"
set -as terminal-features ",alacritty:RGB"

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# options
set -g mouse on
set -g repeat-time 1000
set -g status-position bottom
set -sg escape-time 10
set -g mode-keys vi
set -g focus-events on
set -g history-limit 10000

# reload config
bind r source-file ~/.config/tmux/tmux.conf\; display-message "reloaded"

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -n S-Left  previous-window
bind -n S-Right next-window

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy" 

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
