#####################################################
# Set default terminal
#####################################################
set -g default-terminal "xterm-kitty"
set-option -ga terminal-overrides ",xterm-kitty:Tc"

#####################################################
# Reload config
#####################################################
unbind r
bind r source-file ~/.config/tmux/tmux.conf

#####################################################
# Vim style pane selection
#####################################################
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

#####################################################
# set options
#####################################################
set -g mouse on
set -g default-shell /bin/zsh
set -g repeat-time 1000
set-option -g status-position bottom

#####################################################
# Shift arrow to switch windows
#####################################################
bind -n S-Left  previous-window
bind -n S-Right next-window

#####################################################
# split pane bindings
#####################################################
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

#####################################################
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
#####################################################
run '~/.config/tmux/plugins/tpm/tpm'
